### ISSUE TITLE
How to calculate the loss

### ISSUE THREAD

**Issue by zhangxinqila** [zbloss/reformer_lm#1]
could you tell me what the ouput means when I did like this
``` python
model = ReformerLM(
            vocab_size=model_config['vocab_size'],
            d_in=model_config['n_seq_len'],
            d_out=model_config['n_embd'],
            n_layers=model_config['n_layers'],
            n_heads=model_config['n_heads'],
            attn_k=model_config['attn_k'],
            attn_v=model_config['attn_v'],
        ) 
inputs:  [batch_size,seq_len,dim]=(4,150,100)
output =  model(inputs)
```
thanks

**Comment by zbloss** [comment]
As of now, this outputs the (batch_size, height, width) final hidden state of the model.

If you set your target variable as a masked self-supervised task though, it will return the predicted value. You could then calculate loss as traditionally with transformer models.

**Comment by west30** [comment]
@zhangxinqila 能加微信或者QQ或者邮件交流吗？谢谢。

**Comment by zhangxinqila** [comment]
@west30 onlearningai@163.com
